### PR TITLE
Fixing panic when non array value is passed to array type

### PR DESCRIPTION
**Pull request by andrewmunro**
Encountered a panic similar to issue https://github.com/vektah/gqlgen/issues/110 when passing an object to an array type.

### CODE REVIEW

**Comment by imiskolee** [comment]
@andrewmunro

 can you share an example?

**Comment by vektah** [comment]
Thabks for the pr, a test would be the best way to give an example :)

**Comment by andrewmunro** [comment]
👋 Added a test to the dataloader example to demonstrate this. 

Essentially if you pass an object instead of an array in your query/mutation, gqlgen panics. Handling is not ideal as the field is now ignored with no errors, I imagine this will be fixed properly when @vektah introduces the new parser 🎉! 

For now I hope this is sufficient to prevent app's from panic-ing with malformed input, without having some kind of middleware to recover the application...

**Comment by vektah** [comment]
Yeah that definitely should be caught by validation and give a good message to the user, but the runtime shouldn't panic.

:+1:

**Pull request merged**
